services:
  simulateur:
    build: .
    container_name: sim-entrees-sorties
    restart: unless-stopped
    networks:
      vlan20:
        ipv4_address: 192.168.20.10

networks:
  vlan20:
    external: true