services:
  scada_fuxa:
    build: . 
    image: scada-dev:latest 
    container_name: scada-dev
    restart: unless-stopped
    ports:
      - "1881:1881"
    volumes:
      - ./fuxa_appdata:/usr/src/app/FUXA/server/_appdata
