services:
  simulateur_acide:
    image: simu-rincage-image:latest
    container_name: sim-rincage-modbus
    restart: unless-stopped
    volumes:
      - ./config_simu.json:/app/config_simu.json
    networks:
      vlan20:
        ipv4_address: 192.168.20.10

networks:
  vlan20:
    external: true